### PR TITLE
Simple mathjax support enabled.

### PR DESCRIPTION
**Pull request by mtaung**
Hi @piharpi,

Following some further attempts I managed to get LaTeX support working with mathjax. Please consider this PR to enable this functionality for your repo. Let me know if there are any issues with it.

Best,
MT

### CODE REVIEW

**Comment by piharpi** [comment]
Hello, @mtaung hope you're doing well

I have an issue that completely isn't rendering correctly on the below demo.
image

 Preview: https://klise-git-fork-mtaung-master-piharpi.vercel.app

**Comment by mtaung** [comment]
Hi @piharpi 

This is a fuckup on my part, because I had forgotten to use a separate branch/fork for my own website using this modification of your template. 

Specifically, the only commit needed should be https://github.com/piharpi/jekyll-klise/pull/43/commits/bc94e00bae18f318a9ab55ab4f5416b946f015bf. 

I'll revert back to that commit and set up a new repo for myself as I should've done to start with, sorry.

Best,
Myat Thura

**Comment by mtaung** [comment]
Hi again,

It seems like there are some deeper issues with my implementation. Things work on my computer but not on vercel's render,

**Comment by mtaung** [comment]
Hi,

The maths rendering is not as fast as I'd like so you may want to review the way I've implemented MathJax.

In the meantime, it seems to be working now on vercel's deployments. 

The fix was simply a deprecated CDN that I had copied over, and updating it now has it working properly.

Because I had to force a commit reversion, you may also want to just check that I didn't break anything crazy, but I think it's okay.

Best,
MT

**Pull request merged**
