### PR TITLE
Fix dark light mode flicker

### LINKED ISSUE #25: Flash of dark mode styling when using light mode
**Describe the bug**
When you enable light mode, and click a link/refresh the page, you will see a flash of dark mode styles website before it turns light. This happens everytime you click any link so it's kinda of annoying if you are browsing the site.

**To Reproduce**
1. Go to homepage
2. Click on sun icon to enable light mode
3. Click any link

**Expected behavior**
Light mode to stay light

### PR DESCRIPTION
**Pull request by nickyvanurk**
I started using this theme and fixed #25 myself. JavaScript should be refactored, but instead I would refactor the layouts in general because the doctype, html, and body tag is duplicated multiple times.

This also fixed the dark/light mode not working on the 404 page.

### CODE REVIEW

**Comment by fahmiirsyadk** [comment]
Thank you for submitting this,  @nickyvanurk. I've some revision to optimize the code.

1. **No need manually add a script to initialize the theme on every page**
```html
<body data-theme="{{ site.mode }}" class="notransition">

  <script>
    const body = document.body;
    const data = body.getAttribute("data-theme");

    const initTheme = (state) => {
      if (state === "dark") {
        body.setAttribute("data-theme", "dark");
      } else if (state === "light") {
        body.removeAttribute("data-theme");
      } else {
        localStorage.setItem("theme", data);
      }
    };

    initTheme(localStorage.getItem("theme"));

    setTimeout(() => body.classList.remove("notransition"), 75);
  </script>
```
2. **Transitions problem**
No need to add class `notransition` to disable all transitions, I've tested and faced some element still flashy.
flash

**To fix these issues:**
1. make sure every page in `_layouts` have `data-theme` `<body data-theme="{{ site.mode }}">` , no need add `class="notransition"` and embedded script.

2. Delete script tag main js in `footer.html` and add into `header.html` 
```html
<head prefix="og: http://ogp.me/ns#">
  ...
  <link rel="stylesheet" href="/assets/css/style.css" />
  <!-- add main js script -->
  <script src="/assets/js/main.js" defer="defer"></script>
</head>
```
3. Remove transition in `_base.scss`
```css
// remove this
* {
  -webkit-transition: background-color 75ms ease-in, border-color 75ms ease-in;
  -moz-transition: background-color 75ms ease-in, border-color 75ms ease-in;
  -ms-transition: background-color 75ms ease-in, border-color 75ms ease-in;
  -o-transition: background-color 75ms ease-in, border-color 75ms ease-in;
  transition: background-color 75ms ease-in, border-color 75ms ease-in;
}
```
**That's it, thank you again.**

**Comment by fahmiirsyadk** [comment]
Thank you for submitting this,  @nickyvanurk.

you can remove script tag in `footer.html` and add into `header.html`
```html
<head prefix="og: http://ogp.me/ns#">
  ...
  <link rel="stylesheet" href="/assets/css/style.css" />
  <!-- add main js script -->
  <script src="/assets/js/main.js" defer="defer"></script>
</head>
```
No need to add manually on every page.

**Comment by nickyvanurk** [comment]
Hey @fahmiirsyadk I see you have changed your comment haha?. The notransition class is only for the first render, after that I remove this class as I kinda like to keep transitions on elements, it looks nice. Without it you would still see a flash of darkness when using the light theme because of the 75ms transition. Also on the web it is recommended to keep the JavaScript regarding dark/light theme inline for better performance. Also the remaining JavaScript in main.js is not required at the top of the page, it can't even work that way because the header is still not loaded at that point. Let me know your thoughts.

**Comment by fahmiirsyadk** [comment]
I'm so sorry, the reason I change my comment because it works when I try to deploy it. Before that, (on my local machine) I see border and colors keep flashing from dark to light, I've no idea about that. 

flash

And about the JavaScript, I agree `defer` is the problem

Thanks, for your corrections.

Once again I'm sorry.

**Comment by piharpi** [comment]
Thank you @nickyvanurk and @fahmiirsyadk for discussing this issue
I think #25 dark light mode flicker bug has gone

**Pull request merged**
